### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by daviortega** [theJensenLab/etdb-bulk-download#1]
## Version
`0.1.2`

## Description
When resuming a download with large amount of data, IPFS complains:
```
 Error: open .ipfsRepo/blocks/IU/put-539025496: too many open files
    at parseError (/home/ortegad/Projects/repos/etdb-bulk-download/node_modules/ipfsd-ctl/node_modules/ipfs-api/src/utils/send-request.js:16:17)
    at ClientRequest.<anonymous> (/home/ortegad/Projects/repos/etdb-bulk-download/node_modules/ipfsd-ctl/node_modules/ipfs-api/src/utils/send-request.js:39:14)
    at Object.onceWrapper (events.js:272:13)
    at ClientRequest.emit (events.js:180:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:540:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at Socket.socketOnData (_http_client.js:445:20)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11) code: 0 }
```

Search parameter used:
```
 [                                                                                                                                               
     {
         "type": "filter",
         "searchOn": "artifact.details.speciesName",
         "searchType": "exact",
         "searchFor": "Pseudomonas aeruginosa"
     }
 ]
```

## Platform
Linux 4.9.76-gentoo-r1 x86_64

**Comment by daviortega** [comment]
Just for documentation, could not reproduce it on MacOS
