### ISSUE TITLE
Context deadline exceeded - download pauses then generates error

### ISSUE THREAD

**Issue by Howl0s** [theJensenLab/etdb-bulk-download#4]
```Search parameters accepted
Loading tomograms, please wait - ⠹
Checking for existing local directory ...................... directory not found
Making a new local directory ............................... OK
Creating a new manifest .................................... OK
Analyzing metadata of files ................................ OK
? 
The search parameters selected a 8 records with 16 files with a total of 660.16 MB for download. Would you like to proceed? Yes
Writing metadata...
Initiating download...
 ⠴  QmP7VNtG6vQdiyLurGbjFFbmbxAiKHqerT659NsP7iTTXZ - keymov_ab2011-11-28-6.mp4
   → Progress: 6.29 MB/11.45 MB
    QmP7VNtG6vQdiyLurGbjFFbmbxAiKHqerT659NsP7iTTXZ - keymov_ab2011-11-28-6.flv
    QmPpfVepSxfkgSHnKSNV2NbYCkqcc9493K6d4ybdgSfEqd - keymov_ab2011-11-28-2.mp4
    QmPpfVepSxfkgSHnKSNV2NbYCkqcc9493K6d4ybdgSfEqd - keymov_ab2011-11-28-2.flv
    QmezAf6GNb3BrmYhMnFX26R3G71F94TnWhE9dcgpAwFuJG - keymov_ab2011-11-28-3.mp4
    QmezAf6GNb3BrmYhMnFX26R3G71F94TnWhE9dcgpAwFuJG - keymov_ab2011-11-28-3.flv
    Qmd7Q5jhVsC2y71MLQNaT9qAKMVzdQ9NpYjrfMGmXNnw5K - keymov_ab2011-11-28-7.mp4
    Qmd7Q5jhVsC2y71MLQNaT9qAKMVzdQ9NpYjrfMGmXNnw5K - keymov_ab2011-11-28-7.flv
    QmWjE5EnjLtwc9dyPKk1kdd1q5RePyF42hdXx7bJZmxN5y - keymov_ab2015-08-12-1.mp4
    QmWjE5EnjLtwc9dyPKk1kdd1q5RePyF42hdXx7bJZmxN5y - keymov_ab2015-08-12-1.flv
    QmXoaNGzWdeKV4VwVp1uktVmK1kKTgvsYjhjWabGpVVqgm - keymov_ab2015-08-12-2.mp4
    QmXoaNGzWdeKV4VwVp1uktVmK1kKTgvsYjhjWabGpVVqgm - keymov_ab2015-08-12-2.flv
    QmPnZtUbvUSgEXH2ULr7TFyAAwfmFGDHcmjHsDkiuM2ALP - keymov_ab2015-08-12-3.mp4
    QmPnZtUbvUSgEXH2ULr7TFyAAwfmFGDHcmjHsDkiuM2ALP - keymov_ab2015-08-12-3.flv
    QmXPs8GH5ctLHEJTLzeN1RJVgbyCdLp7uSVKespnTtBim8 - keymov_ab2015-08-12-4.mp4
    QmXPs8GH5ctLHEJTLzeN1RJVgbyCdLp7uSVKespnTtBim8 - keymov_ab2015-08-12-4.flv
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: failed to get block for Qmc75DbiQLaW1raGCDbdNE83hVDod8nBbfhYJx89Mc8Xwz: context deadline exceeded
    at parseError (/Users/alexandria/Documents/GitHub/etdb-downloads/node_modules/ipfs-api/src/utils/send-request.js:16:17)
    at ClientRequest.<anonymous> (/Users/alexandria/Documents/GitHub/etdb-downloads/node_modules/ipfs-api/src/utils/send-request.js:39:14)
    at Object.onceWrapper (events.js:272:13)
    at ClientRequest.emit (events.js:180:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:540:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:445:20)
    at TLSSocket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
Emitted 'error' event at:
    at emitErrorNT (/Users/alexandria/Documents/GitHub/etdb-downloads/node_modules/ipfs-api/node_modules/readable-stream/lib/internal/streams/destroy.js:68:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)

**Comment by Howl0s** [comment]
Restart fixes sometimes but not all the time and it depends on what is being downloaded also [{TiltSeries,Reconstructions,Images,Videos,Others,None}]
